{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2cfa2c16-21d4-47e5-b7bc-0401369cc033",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from PIL import Image\n",
    "\n",
    "# -------------------------------\n",
    "# ⬆️ Load your images (Profile + Project Screenshots)\n",
    "# -------------------------------\n",
    "profile_image = Image.open(\"images/profile.jpg\")  # Change this to your actual image\n",
    "st.set_page_config(page_title=\"Gabriel Oyetunji | Portfolio\", layout=\"centered\")\n",
    "\n",
    "# -------------------------------\n",
    "# 🎨 Custom Dark Theme CSS\n",
    "# -------------------------------\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    body {\n",
    "        background-color: #0e1117;\n",
    "        color: white;\n",
    "    }\n",
    "    .main {\n",
    "        background-color: #0e1117;\n",
    "    }\n",
    "    .project-card {\n",
    "        background-color: #1c1e24;\n",
    "        padding: 20px;\n",
    "        border-radius: 12px;\n",
    "        margin-bottom: 20px;\n",
    "    }\n",
    "    .project-title {\n",
    "        font-size: 24px;\n",
    "        font-weight: bold;\n",
    "        color: #facc15;\n",
    "    }\n",
    "    .tool-tag {\n",
    "        background-color: #374151;\n",
    "        color: white;\n",
    "        padding: 4px 8px;\n",
    "        border-radius: 8px;\n",
    "        margin-right: 5px;\n",
    "        font-size: 13px;\n",
    "        display: inline-block;\n",
    "    }\n",
    "    </style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# -------------------------------\n",
    "# 🙋 Your Name and Info\n",
    "# -------------------------------\n",
    "st.image(profile_image, width=120)\n",
    "st.title(\"Gabriel Oyetunji\")\n",
    "st.subheader(\"Data Analyst | Power BI | Python | SQL\")\n",
    "st.markdown(\"📊 *Turning raw data into sharp insights.*\")\n",
    "\n",
    "# -------------------------------\n",
    "# 🧑‍💼 About Me\n",
    "# -------------------------------\n",
    "about_me = \"\"\"\n",
    "I'm a passionate data analyst with strong skills in data cleaning, automation, and dashboard creation.  \n",
    "I use Power BI, Python, Excel, and SQL to help businesses uncover trends and drive smarter decisions.\n",
    "\"\"\"\n",
    "st.markdown(\"### 🧾 About Me\")\n",
    "st.write(about_me)\n",
    "\n",
    "# -------------------------------\n",
    "# 📜 Certifications\n",
    "# -------------------------------\n",
    "certifications = [\n",
    "    \"✅ Data Analyst – DataCamp (April 2025)\",\n",
    "    \"✅ Excel to MySQL – Coursera (Feb 2024)\",\n",
    "    \"✅ Power BI Advanced – Udemy (Jan 2023)\"\n",
    "]\n",
    "\n",
    "st.markdown(\"### 📑 Certifications\")\n",
    "for cert in certifications:\n",
    "    st.markdown(f\"- {cert}\")\n",
    "\n",
    "# -------------------------------\n",
    "# 📁 Projects Section\n",
    "# -------------------------------\n",
    "st.markdown(\"### 🗂️ Projects\")\n",
    "\n",
    "projects = [\n",
    "    {\n",
    "        \"title\": \"NovaTech Regional Sales Dashboard\",\n",
    "        \"description\": \"Interactive Power BI dashboard tracking monthly sales vs targets across four key regions.\",\n",
    "        \"tools\": [\"Power BI\", \"Excel\", \"Python\"],\n",
    "        \"image\": \"images/project1.png\",\n",
    "        \"github_url\": \"https://github.com/gabrieloyetunji/novatech-sales\",\n",
    "        \"demo_url\": \"https://public.powerbi.com/view?id=example\"\n",
    "    },\n",
    "    {\n",
    "        \"title\": \"F1 Podium Prediction (2023)\",\n",
    "        \"description\": \"A machine learning model predicting which drivers will finish in the top 3 using logistic regression.\",\n",
    "        \"tools\": [\"Python\", \"Scikit-learn\", \"Pandas\"],\n",
    "        \"image\": \"images/project2.png\",\n",
    "        \"github_url\": \"https://github.com/gabrieloyetunji/f1-podium-predictor\",\n",
    "        \"demo_url\": \"\"\n",
    "    }\n",
    "]\n",
    "\n",
    "for project in projects:\n",
    "    st.markdown('<div class=\"project-card\">', unsafe_allow_html=True)\n",
    "    st.markdown(f\"<div class='project-title'>{project['title']}</div>\", unsafe_allow_html=True)\n",
    "    st.markdown(f\"<p>{project['description']}</p>\", unsafe_allow_html=True)\n",
    "\n",
    "    # Tools\n",
    "    tool_tags = \" \".join([f\"<span class='tool-tag'>{tool}</span>\" for tool in project[\"tools\"]])\n",
    "    st.markdown(tool_tags, unsafe_allow_html=True)\n",
    "\n",
    "    # Project image\n",
    "    image = Image.open(project[\"image\"])\n",
    "    st.image(image, use_column_width=True)\n",
    "\n",
    "    # Buttons\n",
    "    if project[\"github_url\"]:\n",
    "        st.markdown(f\"[🔗 GitHub]({project['github_url']})\", unsafe_allow_html=True)\n",
    "    if project[\"demo_url\"]:\n",
    "        st.markdown(f\"[🌐 Live Demo]({project['demo_url']})\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"</div>\", unsafe_allow_html=True)\n",
    "\n",
    "# -------------------------------\n",
    "# 📬 Contact Section\n",
    "# -------------------------------\n",
    "st.markdown(\"### 📬 Contact Me\")\n",
    "st.markdown(\"- 📧 Email: [gabrieloyetunji@example.com](mailto:gabrieloyetunji@example.com)\")\n",
    "st.markdown(\"- 🧠 GitHub: [github.com/gabrieloyetunji](https://github.com/gabrieloyetunji)\")\n",
    "st.markdown(\"- 💼 LinkedIn: [linkedin.com/in/gabrieloyetunji](https://linkedin.com/in/gabrieloyetunji)\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
